[package]
name = "thinkpad-fan-control"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { version = "0.9.0", package = "gtk4", features = ["v4_6"] }
glib = { git = "https://github.com/gtk-rs/gtk-rs-core", branch = "master", features = ["v2_66"] }

